### PR TITLE
Add support for Laravel 10

### PR DESCRIPTION
**Pull request by jackwakefield**

### CODE REVIEW

**Comment by szhorvath** [comment]
@ddzobov When can you merge this in?

**Comment by ddzobov** [comment]
Hello!
I will look on this next week

**Comment by andresilvagomez** [comment]
@ddzobov any news?

**Comment by madman-81** [comment]
Anything we can do to help @ddzobov ? I'd love to see a release with Laravel 10 support so I can upgrade my projects 🤗

**Comment by lucca257** [comment]
this package is useful, I have a pull request opened to use in my company project.

But the project that I`m working on it`s going to be updated to Laravel 10 (next major), so I really need support with the last version of Laravel.

**Comment by ddzobov** [comment]
> this package is useful, I have a pull request opened to use in my company project.
> 
> But the project that I`m working on it`s going to be updated to Laravel 10 (next major), so I really need support with the last version of Laravel.

Did you tested your pull request?
It works, yes?

**Comment by jackwakefield** [comment]
We've been using this change in production at @AlsoAsked since the pull request was made with no issues.

**Pull request merged**
